{% set name = "aenum" %}
{% set version = "3.1.0" %}
{% set sha256 = "87f0e9ef4f828578ab06af30e4d7944043bf4ecd3f4b7bd1cbe37e2173cde94a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - aenum
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ethanfurman/aenum
  license: BSD-3-Clause
  license_family: BSD
  license_file: aenum/LICENSE
  summary: Advanced Enumerations (compatible with Python's stdlib Enum), NamedTuples, and NamedConstants
  dev_url: https://github.com/ethanfurman/aenum
  doc_url: https://github.com/ethanfurman/aenum/blob/master/aenum/doc/aenum.rst

extra:
  recipe-maintainers:
    - sodre
