{% set name = "aenum" %}
{% set version = "3.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ethanfurman/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4c7a5fb76a04ad8dc0c82b13c4cd858b755c69d16c2060a248bf3380a4d1067e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

# >   test_file = os.path.join(tempdir, 'test_json.json')
# E   NameError: name 'tempdir' is not defined
{% set deselect_tests = " --deselect=::TestStackoverflowAnswersV3::test_arduino_headers" %}
{% set deselect_tests = deselect_tests + " --deselect=::TestStackoverflowAnswers::test_arduino_headers" %}
{% set deselect_tests = deselect_tests + " --deselect=::TestEnum::test_meta_reconfigure" %}
{% set deselect_tests = deselect_tests + " --deselect=::test_pickle_dump_load" %}
{% set deselect_tests = deselect_tests + " --deselect=::test_pickle_exception" %}

test:
  imports:
    - aenum
  commands:
    - pip check
    - pytest --pyargs aenum.test {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - pytest-mock

about:
  home: https://github.com/ethanfurman/aenum
  license: BSD-3-Clause
  license_family: BSD
  license_file: aenum/LICENSE
  summary: Advanced Enumerations (compatible with Python's stdlib Enum), NamedTuples, and NamedConstants
  description: |
    An Enum is a set of symbolic names (members) bound to unique, constant values.
    Within an enumeration, the members can be compared by identity, and the enumeration itself can be iterated over.
  dev_url: https://github.com/ethanfurman/aenum
  doc_url: https://github.com/ethanfurman/aenum/blob/master/aenum/doc/aenum.rst

extra:
  recipe-maintainers:
    - sodre
